(function (global) {
  "use strict";
  const KEY = "maiw.privacyConsent", VERSION = 4, PET_ORIGINS = ["http://*/*", "https://*/*"];
  const text = {
    zh: { first: "首次使用", title: "欢迎使用多AI问答助手", lead: "开始前，请选择界面语言、桌宠范围并了解内容会被发送到哪里。", language: "界面语言", pet: "网页桌宠显示范围", petAll: "所有普通网页（推荐）", petSupported: "仅支持的 AI/搜索平台", petText: "选择所有网页时，浏览器会请求一次可选的网站访问权限，仅用于显示桌宠入口；不会因此读取或上传网页内容。", local: "本地保存", localText: "设置、历史、提示词、侧栏草稿和划线笔记保存在当前浏览器中。", send: "发送给所选平台", sendText: "问题、选中文字和附件仅在你主动发送时直接交给所选 AI 平台，并受该平台隐私政策约束。为在工作台内显示官方网页，扩展仅对列明平台的子框架移除 CSP/X-Frame-Options 响应头。", server: "不上传提问数据", serverText: "本插件不设产品账号，不收集遥测，不托管 API 密钥，也不经营问题中转服务。", affiliate: "可选 AI 工具推广", affiliateText: "顶部“AI 工具精选”包含明确标注的推广链接。扩展会从 GitHub Pages 和 Cloudflare Pages 获取公开目录与图标；你通过链接注册或付费时，开发者可能获得佣金。可在设置中隐藏入口。", caution: "请不要向第三方 AI 平台发送密码、身份证号、商业秘密等敏感内容。", privacy: "查看完整隐私政策", go: "了解并继续", foot: "若拒绝网站权限，将自动使用“仅支持平台”模式；可随时在配置中修改。", about: "关于多AI问答助手", aboutText: "免费开源的多平台提问与回答对比工具；独立开发，与所支持平台不存在隶属或合作关系。", developer: "开发者", contact: "联系方式", source: "开源地址", issues: "GitHub Issues", close: "关闭" },
    en: { first: "First use", title: "Welcome to Multi AI Workbench", lead: "Choose your language and pet visibility, then review where your content is sent.", language: "Interface language", pet: "Web pet visibility", petAll: "All regular websites (recommended)", petSupported: "Supported AI/search sites only", petText: "All websites requests optional site access only to render the pet launcher. This permission does not make the extension read or upload page content.", local: "Stored locally", localText: "Settings, history, prompts, side-panel drafts, highlights, and notes stay in this browser.", send: "Sent to selected services", sendText: "Questions, selected text, and files are sent directly to services you choose only when you initiate the action. To display official pages inside the workbench, the extension removes CSP/X-Frame-Options response headers only from listed service subframes. Each service applies its own privacy policy.", server: "No prompt-data server", serverText: "The extension has no product account, telemetry, API-key hosting, or operator-run prompt proxy.", affiliate: "Optional sponsored AI tools", affiliateText: "The Featured AI Tools entry contains clearly labeled affiliate links. The extension fetches a public catalog and icons from GitHub Pages and Cloudflare Pages. The developer may earn a commission if you register or purchase. You can hide the entry in Settings.", caution: "Do not send passwords, identity numbers, trade secrets, or other sensitive content to third-party AI services.", privacy: "Read the full Privacy Policy", go: "Understand and continue", foot: "If site access is declined, the extension falls back to supported sites only. You can change this later in Settings.", about: "About Multi AI Workbench", aboutText: "A free and open-source tool for asking and comparing answers across AI services. It is independently developed and is not affiliated with supported services.", developer: "Developer", contact: "Contact", source: "Source code", issues: "GitHub Issues", close: "Close" }
  };
  const localeOf = (value) => value === "en" ? "en" : "zh";
  const privacyUrl = (locale) => `${chrome.runtime.getURL("privacy/index.html")}?lang=${localeOf(locale)}`;
  function style() {
    if (document.querySelector("#maiwPrivacyStyle")) return;
    const node = document.createElement("style"); node.id = "maiwPrivacyStyle";
    node.textContent = ".maiw-legal-layer{position:fixed;z-index:10000;inset:0;display:grid;place-items:center;padding:20px;background:#0f172aa8;backdrop-filter:blur(8px)}.maiw-legal-card{width:min(560px,100%);max-height:calc(100vh - 40px);overflow:auto;padding:26px;border:1px solid var(--line,#dfe3eb);border-radius:20px;background:var(--panel,#fff);color:var(--text,#172033);box-shadow:0 24px 80px #02061755}.maiw-legal-card h2{margin:4px 0 8px;font-size:24px}.maiw-legal-card p{line-height:1.6}.maiw-legal-eyebrow{color:#4f46e5;font-size:12px;font-weight:800;letter-spacing:.12em}.maiw-legal-lead,.maiw-legal-foot{color:var(--muted,#64748b)}.maiw-language{display:flex;justify-content:space-between;gap:12px;margin:14px 0;padding:11px 13px;border-radius:12px;background:var(--panel-soft,#f6f7fb)}.maiw-disclosures{display:grid;gap:9px}.maiw-disclosure{padding:12px 14px;border:1px solid var(--line,#dfe3eb);border-radius:13px;background:var(--panel-soft,#f8fafc)}.maiw-disclosure strong,.maiw-disclosure span{display:block}.maiw-disclosure span{margin-top:3px;color:var(--muted,#64748b);font-size:13px;line-height:1.55}.maiw-caution{padding:11px 13px;border-radius:11px;background:#fff7ed;color:#9a3412;font-size:13px}.maiw-legal-actions{display:flex;align-items:center;justify-content:flex-end;gap:9px;margin-top:18px}.maiw-legal-actions a{margin-right:auto;color:#4f46e5}.maiw-legal-actions button{min-height:38px;padding:0 16px}.maiw-about-grid{display:grid;grid-template-columns:110px 1fr;gap:10px;margin:20px 0}.maiw-about-grid dd{margin:0}.maiw-placeholder{display:inline-block;min-width:100px;border-bottom:1px dashed var(--line,#cbd5e1);color:var(--muted,#64748b)}@media(max-width:520px){.maiw-legal-card{padding:20px}.maiw-language,.maiw-legal-actions{align-items:stretch;flex-direction:column}.maiw-legal-actions a{margin:0}.maiw-legal-actions button{width:100%}}";
    document.head.append(node);
  }
  async function ensureConsent(options = {}) {
    const stored = await chrome.storage.local.get([KEY, "maiw.settings"]), accepted = stored[KEY];
    let locale = localeOf(options.locale || stored["maiw.settings"]?.locale || (navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en"));
    if (accepted?.version === VERSION) return { accepted: true, locale: localeOf(accepted.locale || locale) };
    style();
    return new Promise((resolve) => {
      const layer = document.createElement("div"); layer.className = "maiw-legal-layer"; layer.setAttribute("role", "dialog"); layer.setAttribute("aria-modal", "true");
      let petScope = "all";
      const render = () => { const t = text[locale]; layer.innerHTML = `<section class="maiw-legal-card"><div class="maiw-legal-eyebrow">${t.first}</div><h2>${t.title}</h2><p class="maiw-legal-lead">${t.lead}</p><label class="maiw-language"><strong>${t.language}</strong><select id="maiwLocale"><option value="zh"${locale === "zh" ? " selected" : ""}>中文</option><option value="en"${locale === "en" ? " selected" : ""}>English</option></select></label><label class="maiw-language"><strong>${t.pet}</strong><select id="maiwPetScope"><option value="all"${petScope === "all" ? " selected" : ""}>${t.petAll}</option><option value="supported"${petScope === "supported" ? " selected" : ""}>${t.petSupported}</option></select></label><div class="maiw-disclosures"><div class="maiw-disclosure"><strong>${t.pet}</strong><span>${t.petText}</span></div><div class="maiw-disclosure"><strong>${t.local}</strong><span>${t.localText}</span></div><div class="maiw-disclosure"><strong>${t.send}</strong><span>${t.sendText}</span></div><div class="maiw-disclosure"><strong>${t.server}</strong><span>${t.serverText}</span></div><div class="maiw-disclosure"><strong>${t.affiliate}</strong><span>${t.affiliateText}</span></div></div><p class="maiw-caution">${t.caution}</p><div class="maiw-legal-actions"><a href="${privacyUrl(locale)}" target="_blank" rel="noopener">${t.privacy}</a><button id="maiwContinue" class="primary">${t.go}</button></div><p class="maiw-legal-foot">${t.foot}</p></section>`;
        layer.querySelector("#maiwLocale").onchange = (event) => { locale = localeOf(event.target.value); render(); };
        layer.querySelector("#maiwPetScope").onchange = (event) => { petScope = event.target.value === "all" ? "all" : "supported"; };
        layer.querySelector("#maiwContinue").onclick = async () => { let launcherScope = petScope; if (launcherScope === "all") { try { if (!await chrome.permissions.request({ origins: PET_ORIGINS })) launcherScope = "supported"; } catch { launcherScope = "supported"; } } const settings = (await chrome.storage.local.get("maiw.settings"))["maiw.settings"] || {}; await chrome.storage.local.set({ [KEY]: { version: VERSION, locale, launcherScope, acceptedAt: new Date().toISOString() }, "maiw.settings": { ...settings, locale, launcherEnabled: true, launcherScope } }); await chrome.runtime.sendMessage({ action: "SYNC_LAUNCHER_SCOPE" }).catch(() => {}); layer.remove(); options.onLocaleChange?.(locale); resolve({ accepted: true, locale, launcherScope }); };
      }; render(); document.body.append(layer);
    });
  }
  const openPrivacy = (locale) => chrome.tabs.create({ url: privacyUrl(locale) });
  function openAbout(localeValue) { style(); const locale = localeOf(localeValue), t = text[locale], layer = document.createElement("div"), profile = "https://github.com/joelovechen", source = `${profile}/multi-ai-workbench`; layer.className = "maiw-legal-layer"; layer.innerHTML = `<section class="maiw-legal-card"><h2>${t.about}</h2><p class="maiw-legal-lead">${t.aboutText}</p><dl class="maiw-about-grid"><dt>${t.developer}</dt><dd><a href="${profile}" target="_blank" rel="noopener">joelovechen</a></dd><dt>${t.contact}</dt><dd><a href="${source}/issues" target="_blank" rel="noopener">${t.issues}</a></dd><dt>${t.source}</dt><dd><a href="${source}" target="_blank" rel="noopener">multi-ai-workbench</a></dd></dl><div class="maiw-legal-actions"><a href="${privacyUrl(locale)}" target="_blank" rel="noopener">${t.privacy}</a><button id="maiwAboutClose">${t.close}</button></div></section>`; const close = () => layer.remove(); layer.onclick = (event) => { if (event.target === layer) close(); }; layer.querySelector("#maiwAboutClose").onclick = close; document.body.append(layer); }
  global.MultiAIPrivacyUI = Object.freeze({ ensureConsent, openPrivacy, openAbout, privacyUrl });
})(globalThis);
